

obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_common.o
obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_main.o
#obj-y += mstar_drv_mutual_fw_control.o
obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_self_fw_control.o
obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_ic_fw_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_platform_porting_layer.o
obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_platform_interface.o
obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_utility_adaption.o
obj-$(CONFIG_TOUCHSCREEN_CATA_MSG2238) += mstar_drv_qcom.o

